// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jHeAHQGWFXSEAzMmXFCEk5N2tm7up5w',
    appId: '1:855830665088:web:019efafa8c6882f480d365',
    messagingSenderId: '855830665088',
    projectId: 'clubapp1-5874a',
    authDomain: 'clubapp1-5874a.firebaseapp.com',
    storageBucket: 'clubapp1-5874a.firebasestorage.app',
    measurementId: 'G-BDN0X2QDJQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vQctGPwN3y_o6mm3Ns3BLL8oCu-zmjQ',
    appId: '1:855830665088:ios:8882f285b0d50b0480d365',
    messagingSenderId: '855830665088',
    projectId: 'clubapp1-5874a',
    storageBucket: 'clubapp1-5874a.firebasestorage.app',
    iosBundleId: 'com.example.clubaikya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vQctGPwN3y_o6mm3Ns3BLL8oCu-zmjQ',
    appId: '1:855830665088:ios:8882f285b0d50b0480d365',
    messagingSenderId: '855830665088',
    projectId: 'clubapp1-5874a',
    storageBucket: 'clubapp1-5874a.firebasestorage.app',
    iosBundleId: 'com.example.clubaikya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jHeAHQGWFXSEAzMmXFCEk5N2tm7up5w',
    appId: '1:855830665088:web:c078789a306348a780d365',
    messagingSenderId: '855830665088',
    projectId: 'clubapp1-5874a',
    authDomain: 'clubapp1-5874a.firebaseapp.com',
    storageBucket: 'clubapp1-5874a.firebasestorage.app',
    measurementId: 'G-QRWP4RF0ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDamFIS3_66v3P9WThvU4KDxd0qd8MsT4',
    appId: '1:855830665088:android:ceb4f358243eb70b80d365',
    messagingSenderId: '855830665088',
    projectId: 'clubapp1-5874a',
    storageBucket: 'clubapp1-5874a.firebasestorage.app',
  );

}